# Generated by Django 2.2.13 on 2020-09-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cityinfo',
            table='city_info',
        ),
    ]
