version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sms_group
      - POSTGRES_USER=gyan
      - POSTGRES_PASSWORD=gyan123
  backend:
    build:
      context: ./
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata --app city_info fixtures.json &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    container_name: backend_sms_grp
    depends_on: 
      - db
  frontend:
    build:
      context: ./city_app_frontend
      args:
        API_URL: http://localhost/api/
    volumes:
      - build_folder:/frontend/build/
    container_name: frontend_sms_grp
    restart: on-failure
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend/
    depends_on:
      - backend
      - frontend
    container_name: nginx
volumes:
  build_folder: