version: '3'

services:
  backend:
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: backend_sms_grp
  frontend:
    build:
      context: ./city_app_frontend
      args:
        API_URL: http://localhost/api/
    command: npm start
    port:
      - "3000:3000"
    volumes:
      - build_folder:/city_app_frontend/build
    container_name: frontend_sms_grp
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
    container_name: nginx
volumes:
  build_folder: